### ISSUE TITLE
assert/error on simple pdf

### ISSUE THREAD

**Issue by davea42** [JohannesBuchner/research2epub#1]
I tried research2epub on a simple one page pdf and it gets an assert.   

The real  attempt was to make an epub of a 400 page pdf
our open source committee is creating with Latex (latex approaches to generate
epub or html are not working on the document so far).  So I randomly
picked a one page pdf and applied research2epub  and...no luck there either.

On the large document:
Traceback (most recent call last):
  File "findspaces.py", line 312, in <module>
    values = get_line_filled2(p, seg)
  File "findspaces.py", line 269, in get_line_filled2
    assert rect.shape == (seg['right'] - seg['left'] + 1, seg['bottom'] - seg['top'] + 1)

On the one page pdf the last lines of output are:
361 nan nan 0.329090909091
362 nan nan 0.33
363 nan nan 0.330909090909
364 nan nan 0.331818181818
365 nan nan 0.332727272727
Traceback (most recent call last):
  File "findspaces.py", line 127, in <module>
    lrtb, region = find_borders(pages)
  File "findspaces.py", line 102, in find_borders
    assert i < shape[0] / 3
AssertionError

**Comment by JohannesBuchner** [comment]
Strange. It seems similar() is returning nans. Do you have near-empty pages?

convert.sh first creates png images from the input pdf.
findspaces.py then analyses input png pages for their structure, and should write out a json file
describing the found segments.

**Comment by davea42** [comment]
On 02/17/2014 06:45 AM, Johannes Buchner wrote:

> Strange. It seems similar() is returning nans. Do you have near-empty 
> pages?
> 
> convert.sh first creates png images from the input pdf.
> findspaces.py then analyses input png pages for their structure, and 
> should write out a json file
> describing the found segments.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/JohannesBuchner/research2epub/issues/1#issuecomment-35287473.

Near-empty is a phrase  that does not seem to reflect the situation.

The attached 37KByte pdf is a wiring diagram of
a gate-opener system (the pdf is freely available to anyone
on the internet).  The page looks quite full...to me.

DavidA.

## 

Every generalization is false, including this one. -- Mark Twain

**Comment by JohannesBuchner** [comment]
Unfortunately, the file did not arrive.

**Comment by davea42** [comment]
On 02/17/2014 08:57 AM, Johannes Buchner wrote:

> Unfortunately, the file did not arrive.
> 
> I was afraid of that. Sensible stripping of attachments.

```
   wget www.prevanders.net/powermaster6002-rsg.pdf
```

will, for a few hours, get you the file to try out.

DavidA.

## 

Every generalization is false, including this one. -- Mark Twain

**Comment by JohannesBuchner** [comment]
I see now what is going wrong. For getting the borders (headers and footers) I compute the similar areas across pages. For that I discard the first page, and look at all even and all odd pages from there on. With only one page, this algorithm does not work and always returns the same number.

**Comment by davea42** [comment]
The large document I was originally trying is 'report' style
for now (memoir is the latex package
involved)so  no left-right is involved. BTW.

**Comment by JohannesBuchner** [comment]
I am sorry it is not working for you. You could add some prints (checking what rect, seg are set to) to investigate. Currently I am not developing or using this code.

**Comment by davea42** [comment]
Perhaps I am clueless, but lines 101, 102 of findspaces.py make little sense to me.
        for i in range(shape[0] / 2):
            assert i < shape[0] / 3
Not that this is a big issue, but how could it ever work?
Not expecting help, just saying...

**Comment by davea42** [comment]
I got it to work on a couple documents with, in the end, not much effort.
I doubt we'll use it on our big document, but I applaud your work here,
it is a clever idea and imaginative use of tools. 
Thanks for making it available.

**Comment by davea42** [comment]
This is what I did to get it to basically work for me
as a trial.    Some of the diff lines look odd
because I used spaces and you use tabs.
Should be clear enough anyway.
I did not bother with making a one page
document work.

Thanks again for making research2epub available.

diff --git a/findspaces.py b/findspaces.py
index 49fcaa5..8619dbf 100644
--- a/findspaces.py
+++ b/findspaces.py
@@ -66,6 +66,8 @@ cache = lambda x: x
  # compute overlap / similarities among pages
  @cache
  def similar(pages, selection):
-        if not selection.any():
-            return None
    assert selection.any()
    parts = [p[selection] for p in pages]
    first = parts[0]
  @@ -77,6 +79,8 @@ def similar(pages, selection):
    diffs += [(e != even[0]).sum() for e in even[1:]]
    assert not numpy.isnan(diffs).any(), diffs
    #print 'similar:', sum(diffs), 'of', selection.size, 'across %d 
  pages' % (len(pages))
-        if len(diffs) == 0:
- ```
         return None
  ```
  
    return numpy.mean(diffs) \* 1. / size
  
  # find common stuff along borders
  
  @@ -99,10 +103,13 @@ def find_borders(pages):
        print 'constraint for %d: ' % dim + ('indices[%d] >= shape[%d] 
- i' % (dim/2, dim/2) if dim % 2 == 1 else 'indices[%d] <= i' % (dim/2))
        values = []
        for i in range(shape[0] / 2):
-            assert i < shape[0] / 3
-            # Following assert seems crazy.
-            #assert i < shape[0] / 3
            region_add = indices[dim/2] >= shape[dim/2] - i if dim % 2 
  == 1 else indices[dim/2] <= i
            region_next = numpy.logical_or(region, region_add)
            v = similar(pages, region_next)
-                        if v == None:
-                                continue;
            print i, v, v - v0, region_next.sum() \* 1. / region_next.size
            values.append([i, v - v0])
            if last_v is None or last_v == v:
  @@ -117,7 +124,8 @@ def find_borders(pages):
                v0 = similar(pages, region)
                break
        values = numpy.array(values)
-        plt.plot(values[:,0], values[:,1], 'x-', label='dim=%d' % dim)
-                if len(values) != 0:
-            plt.plot(values[:,0], values[:,1], 'x-', label='dim=%d' % dim)
    plt.legend(loc='best', ncol=2)
    if debug:
        plt.savefig('borders.pdf', bbox_inches='tight')
  @@ -131,11 +139,13 @@ l, r, t, b = lrtb
  def totaldiff(region):
      return numpy.mean([p[region].sum() for p in pages]) \* 1. / size

-# centrally, at (l + r) / 2, there is a white band of a certain size.
+# Centrally, at (l + r) / 2, there can be a white band of a certain size
+# if it is parallel columns.
  mid = (l + shape[0] - r) / 2

  # determine how wide it is
  values = []
+# shape[0] is page width (typically 850).
  for i in range(shape[0] / 10):
      region_band = multi_and(indices[0] >= mid - i,
              indices[0] <= mid + i, -region)
@@ -338,6 +348,7 @@ for j, v in enumerate(vals):
      if v == 0:
          break
  print 'flat starting', j
+print 'flats :', flats
  flat_heights = bins[flats]
  print 'flat heights:', flat_heights
  h = bins[j]
@@ -351,8 +362,9 @@ pages_sub_segments = []
  for i, (p, segments, seg_coords) in enumerate(zip(pages, 
segments_pages, page_coords)):
      sub_segments = []
      print 'splitting segments for page %d' % i
-    assert len(seg_coords) == len(segments)
-    for seg, coords in zip(segments, seg_coords):
-    #assert len(seg_coords) == len(segments)
-        if len(seg_coords) == len(segments):
-      for seg, coords in zip(segments, seg_coords):
        # split into sub-segments if they are smaller than h
        splitters = [(lo, hi) for lo, hi in coords if hi - lo > h]
        # parts are between splitters
  diff --git a/rewrite.py b/rewrite.py
  index 55801cc..22bbe75 100644
  --- a/rewrite.py
  +++ b/rewrite.py
  @@ -12,6 +12,10 @@ from PIL import Image
  import json
  from math import floor, ceil

+# This would be better if controlled
+# by command line.
+allowrotate = False
+
  #info = json.load(open(sys.argv[2]))
  from PyPDF2 import PdfFileWriter, PdfFileReader
  origfile = PdfFileReader(open(sys.argv[2], 'rb'))
@@ -82,7 +86,7 @@ for f, im, segments in zip(infiles, images, 
pages_sub_segments):
          bbox_height = (bbox[3] - bbox[1])
          scale = 1.
          rotate = False
-        if not is_col:
-        if allowrotate == True and not is_col:
            # scale to width
            scale = max(width \* 1. / colwidth, 1)
            # if it happens that something is wider (by a factor of 2)

**Comment by JohannesBuchner** [comment]
The for loop tries to truncates the page e.g. from the left to the middle in pixel steps
   for i in range(shape[0] / 2):
However, once content is encountered, it should stop (using the break statement in the loop). It is not expected that the document is entirely empty, so that step should be reached soon, i.e. before 33% of the page has been truncated. That's why I put an assert there, to check against strange documents.

Thanks for investing time and looking into the issue.
What you can also do is to look how findspaces.py created the json file that describes how to truncate the pages. If you know your document well, you can create such a file by hand, and use the other tools to create a re-flowed document.
